import Head from 'next/head'
import { Form, Projects, Button } from '../components'
import { useState } from 'react'




export default function Home() {
  const [isOpen, setIsOpen] = useState(false)

  const onClickOpen = () => {
    setIsOpen(true);
  }
  const onClickClose = () => {
    setIsOpen(false);
  };
  const handleFormSubmit = () => {
    setIsOpen(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex-block justify-center mx-20 mt-14 px-10 py-2 ">
        <Projects />
        {isOpen ? <Form onClick={onClickClose} isOpen={isOpen} handleSubmit={handleFormSubmit} /> : <Button onClick={onClickOpen} name='Add Project+' />}
      </main>
    </>
  )
}
